name: 'Git Check Clean Tree'
description: 'Check Git Clean Tree'
inputs:
  error-reason:
    description: 'Check reason for Git Tree not to be clean'
    required: true
    default: "Last command"
runs:
  using: "composite"
  steps:
    - name: check if the git tree is clean
      run: |
        if [[ -n $(git status -s) ]]; 
        then
          echo "ERROR: tree is dirty after ${{ inputs.error-reason }}"
          git status
          exit 1
        else
          echo "Working tree is clean."
        fi
      shell: bash

branding:
  icon: "activity"
  color: "blue"
