name: 'Git Check Clean Tree'
description: 'Check Git Clean Tree'
inputs:
  error-reason:
    description: 'Check reason for Git Tree not to be clean'
    required: true
    default: "Last command"
runs:
  using: "composite"
  steps:
    - run: |
        ./clean-tree-check.sh ${{ inputs.error-reason }}
      shell: bash

branding:
  icon: "activity"
  color: "blue"
