name: "Test Action"

on:
  workflow_dispatch:


jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Git Clean Tree
        uses: ArkadiK94/action-git-clean-tree@v1
      - uses: ./
        with:
          error-reason: last command
            
