name: "Test Action"

on:
  workflow_dispatch:


jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          error-reason: last command
            
